import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header";
import AuthProvider from "./AuthProvider";

export const metadata: Metadata = {
	title: "Next APP",
	description: "Generated by Tomas Chlebek",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<AuthProvider>
					<Header />
					<div className="mx-auto max-w-7xl p-3 sm:p-6">{children}</div>
				</AuthProvider>
			</body>
		</html>
	);
}
